import { StyleSheet } from "react-native";

import { palette } from "@/constants/theme";
import type { useTheme } from "@/hooks/useTheme";

export const ORANGE = "#FF7A1A";
export const SOFT_ORANGE = "#FFB36B";

export function makeStyles(C: ReturnType<typeof useTheme>) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: "#050505",
    },
    safeArea: {
      flex: 1,
      zIndex: 10,
    },
    flex: {
      flex: 1,
    },
    progressRow: {
      paddingHorizontal: 22,
      paddingTop: 8,
      paddingBottom: 6,
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    backBtn: {
      width: 24,
      height: 24,
      alignItems: "flex-start",
      justifyContent: "center",
    },
    progressTrack: {
      flex: 1,
    },
    screen: {
      flex: 1,
      paddingHorizontal: 22,
      paddingBottom: 24,
      justifyContent: "space-between",
      gap: 18,
    },
    screenSticky: {
      justifyContent: "flex-start",
    },
    screenContent: {
      flex: 1,
      justifyContent: "flex-start",
      gap: 26,
      paddingTop: 24,
    },
    scrollContent: {
      paddingTop: 24,
      paddingBottom: 24,
      gap: 20,
    },
    copyBlock: {
      gap: 12,
    },
    headline: {
      color: "#fff",
      fontSize: 30,
      lineHeight: 34,
      fontWeight: "800",
    },
    body: {
      color: palette.white75,
      fontSize: 15,
      lineHeight: 22,
      fontWeight: "500",
    },
    primaryButton: {
      minHeight: 56,
      borderRadius: 8,
      backgroundColor: C.accent,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.14)",
      shadowColor: C.accent,
      shadowOpacity: 0.24,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 8 },
    },
    primaryButtonDisabled: {
      backgroundColor: C.accentBgSubtle,
      borderColor: C.accentBorderSubtle,
      shadowOpacity: 0,
    },
    primaryButtonText: {
      color: "#fff",
      fontSize: 16,
      fontWeight: "800",
    },
    primaryButtonTextDisabled: {
      color: C.textTertiary,
    },
    heroVisual: {
      height: 292,
      overflow: "hidden",
      borderRadius: 8,
      backgroundColor: "rgba(255,255,255,0.01)",
    },
    heroGlow: {
      position: "absolute",
      top: 42,
      alignSelf: "center",
      width: 230,
      height: 230,
      borderRadius: 115,
      backgroundColor: "rgba(255,249,230,0.24)",
      shadowColor: "#FFF3D7",
      shadowOpacity: 0.44,
      shadowRadius: 46,
    },
    heroCloudOne: {
      position: "absolute",
      top: 78,
      right: 38,
      width: 92,
      height: 30,
      borderRadius: 15,
      backgroundColor: "rgba(255,255,255,0.09)",
      transform: [{ rotate: "3deg" }],
    },
    heroCloudTwo: {
      position: "absolute",
      top: 138,
      left: 64,
      width: 86,
      height: 26,
      borderRadius: 13,
      backgroundColor: "rgba(255,255,255,0.055)",
      transform: [{ rotate: "-7deg" }],
    },
    hillBack: {
      position: "absolute",
      bottom: 24,
      left: -72,
      width: 330,
      height: 132,
      borderTopLeftRadius: 220,
      borderTopRightRadius: 220,
      backgroundColor: "#060606",
      transform: [{ rotate: "8deg" }],
    },
    hillFront: {
      position: "absolute",
      bottom: -20,
      right: -90,
      width: 390,
      height: 162,
      borderTopLeftRadius: 260,
      borderTopRightRadius: 260,
      backgroundColor: "#050505",
      transform: [{ rotate: "-7deg" }],
    },
    sun: {
      position: "absolute",
      bottom: 42,
      alignSelf: "center",
      width: 72,
      height: 72,
      borderRadius: 36,
      backgroundColor: ORANGE,
      shadowColor: ORANGE,
      shadowOpacity: 0.55,
      shadowRadius: 34,
    },
    floatingTag: {
      position: "absolute",
      zIndex: 4,
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingHorizontal: 12,
      height: 32,
      borderRadius: 16,
      backgroundColor: "rgba(0,0,0,0.86)",
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.12)",
    },
    tagDot: {
      width: 4,
      height: 4,
      borderRadius: 2,
      backgroundColor: SOFT_ORANGE,
    },
    floatingTagText: {
      color: "#fff",
      fontSize: 11,
      fontWeight: "800",
    },
    cardList: {
      gap: 10,
    },
    painIntro: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 14,
    },
    painIntroCopy: {
      flex: 1,
      gap: 12,
    },
    painSectionList: {
      gap: 18,
      paddingBottom: 4,
    },
    painSection: {
      gap: 9,
    },
    painSectionHeader: {
      minHeight: 24,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 2,
    },
    painSectionTitleWrap: {
      flexDirection: "row",
      alignItems: "center",
      gap: 7,
    },
    painSectionTitle: {
      color: palette.white70,
      fontSize: 12,
      fontWeight: "800",
      textTransform: "uppercase",
    },
    painSectionToggle: {
      width: 28,
      height: 28,
      borderRadius: 14,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "rgba(255,179,107,0.10)",
      borderWidth: 1,
      borderColor: "rgba(255,179,107,0.18)",
    },
    painChoiceList: {
      gap: 8,
    },
    painChoice: {
      minHeight: 48,
      borderRadius: 8,
      paddingHorizontal: 14,
      paddingVertical: 12,
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      backgroundColor: "#141414",
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.06)",
    },
    painChoiceActive: {
      backgroundColor: "rgba(255,122,26,0.14)",
      borderColor: "rgba(255,122,26,0.44)",
      shadowColor: ORANGE,
      shadowOpacity: 0.16,
      shadowRadius: 14,
    },
    painChoiceText: {
      flex: 1,
      color: palette.white80,
      fontSize: 13,
      lineHeight: 18,
      fontWeight: "700",
    },
    painChoiceTextActive: {
      color: "#fff",
    },
    choiceCard: {
      minHeight: 54,
      borderRadius: 8,
      paddingHorizontal: 14,
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      backgroundColor: "#141414",
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.06)",
    },
    choiceCardActive: {
      backgroundColor: "rgba(255,122,26,0.14)",
      borderColor: "rgba(255,122,26,0.44)",
      shadowColor: ORANGE,
      shadowOpacity: 0.2,
      shadowRadius: 18,
    },
    dimmed: {
      opacity: 0.45,
    },
    choiceText: {
      flex: 1,
      color: "#fff",
      fontSize: 14,
      lineHeight: 19,
      fontWeight: "700",
    },
    chartCard: {
      borderRadius: 8,
      padding: 18,
      minHeight: 248,
      backgroundColor: "#111111",
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.07)",
      justifyContent: "space-between",
    },
    futureCopy: {
      marginTop: 10,
    },
    chartTitle: {
      color: "#fff",
      fontSize: 14,
      fontWeight: "800",
    },
    chartAxis: {
      flexDirection: "row",
      justifyContent: "space-between",
      paddingHorizontal: 8,
    },
    axisLabel: {
      color: palette.white35,
      fontSize: 11,
      fontWeight: "700",
    },
    nameFieldWrap: {
      gap: 8,
    },
    fieldLabel: {
      color: palette.white70,
      fontSize: 12,
      fontWeight: "800",
      textTransform: "uppercase",
      letterSpacing: 1,
    },
    nameInput: {
      minHeight: 58,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.10)",
      backgroundColor: "rgba(255,255,255,0.06)",
      paddingHorizontal: 16,
      color: "#fff",
      fontSize: 17,
      fontWeight: "700",
    },
    avatarGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      columnGap: 8,
      rowGap: 10,
      paddingBottom: 12,
    },
    avatarChoice: {
      flexBasis: "31.8%",
      flexGrow: 1,
      maxWidth: "31.8%",
      borderRadius: 8,
      backgroundColor: "#141414",
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.07)",
      padding: 6,
      gap: 6,
    },
    avatarChoiceActive: {
      borderColor: "rgba(255,122,26,0.72)",
      backgroundColor: "rgba(255,122,26,0.12)",
    },
    characterAvatarFrame: {
      width: "100%",
      aspectRatio: 1,
      borderRadius: 7,
      overflow: "hidden",
      backgroundColor: "rgba(255,255,255,0.05)",
    },
    characterAvatarImage: {
      width: "100%",
      height: "100%",
    },
    avatarCheckBadge: {
      position: "absolute",
      top: 7,
      right: 7,
      width: 24,
      height: 24,
      borderRadius: 12,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: ORANGE,
      borderWidth: 2,
      borderColor: "#141414",
    },
    avatarChoiceText: {
      color: palette.white70,
      fontSize: 10,
      fontWeight: "800",
      lineHeight: 13,
      textAlign: "center",
    },
    avatarChoiceTextActive: {
      color: "#fff",
    },
    timelineCard: {
      minHeight: 94,
      borderRadius: 8,
      padding: 16,
      backgroundColor: "#141414",
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.06)",
      flexDirection: "row",
      alignItems: "center",
      gap: 14,
    },
    timelineIcon: {
      width: 54,
      height: 54,
      borderRadius: 27,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "rgba(255,122,26,0.10)",
    },
    cardTitle: {
      color: SOFT_ORANGE,
      fontSize: 16,
      fontWeight: "800",
      marginBottom: 3,
    },
    smallLine: {
      color: palette.white70,
      fontSize: 12,
      lineHeight: 17,
      fontWeight: "600",
    },
    ratingRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    avatarStack: {
      flexDirection: "row",
    },
    avatarImage: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: "rgba(255,255,255,0.14)",
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.7)",
    },
    starRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 2,
    },
    ratingText: {
      color: palette.white70,
      fontSize: 12,
      fontWeight: "700",
    },
    statsRow: {
      flexDirection: "row",
      gap: 10,
    },
    statCard: {
      flex: 1,
      minHeight: 118,
      borderRadius: 8,
      padding: 13,
      justifyContent: "center",
      backgroundColor: "#141414",
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.06)",
      gap: 8,
    },
    statValue: {
      color: SOFT_ORANGE,
      fontSize: 24,
      fontWeight: "800",
    },
    statLabel: {
      color: palette.white70,
      fontSize: 11,
      lineHeight: 16,
      fontWeight: "700",
    },
    reviewList: {
      gap: 10,
      paddingBottom: 2,
    },
    reviewCard: {
      borderRadius: 8,
      padding: 14,
      backgroundColor: "#141414",
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.06)",
      gap: 10,
    },
    reviewHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    reviewAvatar: {
      width: 34,
      height: 34,
      borderRadius: 17,
      backgroundColor: "rgba(255,255,255,0.14)",
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.12)",
    },
    reviewName: {
      color: "#fff",
      fontSize: 13,
      lineHeight: 17,
      fontWeight: "800",
    },
    reviewRole: {
      color: palette.white45,
      fontSize: 11,
      lineHeight: 15,
      fontWeight: "700",
    },
    reviewStars: {
      flexDirection: "row",
      alignItems: "center",
      gap: 1,
    },
    reviewText: {
      color: palette.white70,
      fontSize: 13,
      lineHeight: 19,
      fontWeight: "600",
    },
    keyboard: {
      flex: 1,
    },
    goalInput: {
      minHeight: 78,
      borderRadius: 8,
      paddingHorizontal: 16,
      paddingVertical: 16,
      color: "#fff",
      fontSize: 15,
      lineHeight: 21,
      backgroundColor: "#141414",
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.06)",
      textAlignVertical: "top",
    },
    goalSuggestionList: {
      gap: 8,
    },
    goalSuggestion: {
      minHeight: 46,
      borderRadius: 8,
      paddingHorizontal: 14,
      paddingVertical: 11,
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      backgroundColor: "#141414",
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.06)",
    },
    goalSuggestionActive: {
      backgroundColor: "rgba(255,122,26,0.14)",
      borderColor: "rgba(255,122,26,0.44)",
    },
    goalSuggestionText: {
      flex: 1,
      color: palette.white80,
      fontSize: 13,
      lineHeight: 18,
      fontWeight: "700",
    },
    goalSuggestionTextActive: {
      color: "#fff",
    },
    choiceReason: {
      color: palette.white45,
      fontSize: 11,
      fontWeight: "600",
      marginTop: 2,
    },
    painReminder: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 6,
    },
    painTag: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 20,
      backgroundColor: "rgba(255,179,107,0.10)",
      borderWidth: 1,
      borderColor: "rgba(255,179,107,0.25)",
    },
    painTagText: {
      color: SOFT_ORANGE,
      fontSize: 11,
      fontWeight: "700",
    },
    habitCard: {
      borderRadius: 14,
      paddingHorizontal: 16,
      paddingVertical: 16,
      flexDirection: "row",
      alignItems: "center",
      gap: 14,
      backgroundColor: "#141414",
      borderWidth: 1.5,
      borderColor: "rgba(255,255,255,0.06)",
    },
    habitCardActive: {
      backgroundColor: "rgba(255,122,26,0.10)",
      borderColor: "rgba(255,122,26,0.5)",
    },
    habitIconWrap: {
      width: 46,
      height: 46,
      borderRadius: 12,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "rgba(255,255,255,0.06)",
    },
    habitIconWrapActive: {
      backgroundColor: "rgba(255,122,26,0.15)",
    },
    habitTitle: {
      color: palette.white70,
      fontSize: 15,
      fontWeight: "700",
      marginBottom: 3,
    },
    habitTitleActive: {
      color: "#fff",
    },
    habitSubtitle: {
      color: palette.white45,
      fontSize: 12,
      fontWeight: "500",
      lineHeight: 17,
    },
    customHabitInput: {
      color: "#fff",
      fontSize: 15,
      fontWeight: "700",
      paddingVertical: 0,
    },
    tourCard: {
      borderRadius: 14,
      paddingHorizontal: 16,
      paddingVertical: 18,
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 14,
      backgroundColor: "#141414",
      borderWidth: 1.5,
      borderColor: "rgba(255,255,255,0.06)",
    },
    tourIconWrap: {
      width: 46,
      height: 46,
      borderRadius: 12,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "rgba(255,122,26,0.12)",
      borderWidth: 1,
      borderColor: "rgba(255,122,26,0.25)",
      marginTop: 2,
    },
    tourTitleRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      marginBottom: 3,
    },
    tourTab: {
      color: SOFT_ORANGE,
      fontSize: 11,
      fontWeight: "800",
      textTransform: "uppercase",
      letterSpacing: 0.5,
    },
    tourTitle: {
      color: "#fff",
      fontSize: 15,
      fontWeight: "700",
      marginBottom: 5,
    },
    tourDescription: {
      color: palette.white55,
      fontSize: 13,
      lineHeight: 19,
      fontWeight: "500",
    },
    focusGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 12,
    },
    focusCard: {
      width: "47%",
      minHeight: 100,
      borderRadius: 14,
      paddingVertical: 18,
      paddingHorizontal: 14,
      alignItems: "center",
      justifyContent: "center",
      gap: 10,
      backgroundColor: "#141414",
      borderWidth: 1.5,
      borderColor: "rgba(255,255,255,0.06)",
    },
    focusCardActive: {
      backgroundColor: "rgba(255,122,26,0.10)",
      borderColor: "rgba(255,122,26,0.5)",
    },
    focusIconWrap: {
      width: 50,
      height: 50,
      borderRadius: 14,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "rgba(255,255,255,0.06)",
    },
    focusIconWrapActive: {
      backgroundColor: "rgba(255,122,26,0.15)",
    },
    focusLabel: {
      color: palette.white70,
      fontSize: 14,
      fontWeight: "700",
      textAlign: "center",
    },
    focusLabelActive: {
      color: "#fff",
    },
    focusCheck: {
      position: "absolute",
      top: 10,
      right: 10,
    },
    amplifyList: {
      gap: 14,
    },
    amplifyCard: {
      borderRadius: 14,
      padding: 16,
      gap: 10,
      backgroundColor: "#141414",
      borderWidth: 1.5,
      borderColor: "rgba(255,80,80,0.18)",
    },
    amplifyPainRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 7,
    },
    amplifyPainText: {
      color: SOFT_ORANGE,
      fontSize: 13,
      fontWeight: "800",
      flex: 1,
    },
    amplifyHarm: {
      color: "#fff",
      fontSize: 14,
      lineHeight: 21,
      fontWeight: "600",
    },
    amplifyCostRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 6,
      paddingTop: 4,
      borderTopWidth: 1,
      borderTopColor: "rgba(255,255,255,0.06)",
    },
    amplifyCost: {
      color: palette.white55,
      fontSize: 12,
      lineHeight: 18,
      fontWeight: "500",
      flex: 1,
    },
  });
}
